commit af86dd3f94c6e457a9c5ae8ee0af5f9ae4fa9ffd
Author: Alexander Moibenko <moibenko@fnal.gov>
Date:   Thu Dec 17 14:35:52 2020 -0600

    enstore rpm 6.3.4-5

A	release-notes/ENSTORE_V_6.3.4-4.txt
M	spec/enstore_RH7_python_2.7.16_with_start_on_boot.spec

commit e6652430d695e467e73fa43308a221e510762f82
Author: Alexander Moibenko <moibenko@fnal.gov>
Date:   Wed Dec 9 12:33:14 2020 -0600

    Ratekeeper hangs getting status from dead mover.
    
    When ratekeeper tries to get status from the dead mover it waits longer than a lifetime of the process.
    
    https://uqbar.fnal.gov/reviews/r/677/
    https://uqbar.fnal.gov/reviews/r/677/bugs/2356/

M	etc/config_params.html
M	src/ratekeeper.py

commit e6a7c9e8b72812d4c8170fba0d8b1b217c3c06fc
Author: Dmitry Litvintsev <litvinse@fnal.gov>
Date:   Fri Nov 13 13:58:48 2020 -0600

    checkdb_PITR: get it to work properly

M	src/checkdb_PITR.py

commit 3e10fa7dc0db2cc251597305e4cad149a7c19155
Author: Alexander Moibenko <moibenko@fnal.gov>
Date:   Thu Nov 12 13:24:39 2020 -0600

    Modify volume_assert to not stop on errors.
    
    When running volume_assert on FL0016L8 recovery tape, it periodically gets an FTT_EBUSY POSITIONING error which stops the assert.  If at all possibly please modify it so it does not stop when this happens.  IBM does not see any errors (at least for the one I got dump from drive when it occurred for location 29.
    
    http://srm.fnal.gov/reviews/r/669/
    http://www-ccf.fnal.gov/Bugzilla/show_bug.cgi?id=2325

M	src/mover.py

commit 93174a25f1a045569d5b455dc7c95d6e9cd836e0
Author: Dmitry Litvintsev <litvinse@fnal.gov>
Date:   Fri Nov 6 11:45:48 2020 -0600

    enrcp, enrsh : allow postgres to copy to enstore
    wal script: changes to avoid errors generated by setup enstore
    
    RB : http://uqbar.fnal.gov/reviews/r/674/

M	sbin/enrcp
M	sbin/enrsh
M	tools/wal_backup.sh

commit 21d84dd24a8588fc7e76bd20f4bc9e440c2a8fbc
Author: Alexander Moibenko <moibenko@fnal.gov>
Date:   Tue Oct 27 14:33:36 2020 -0500

    Add Enstore environment variables to sudoers.
    
    These variables were missing causing calls of rsh instead of SSH.
    
    http://srm.fnal.gov/reviews/r/668/
    http://www-ccf.fnal.gov/Bugzilla/show_bug.cgi?id=2321

M	spec/enstore_RH7_python_2.7.16_with_start_on_boot.spec

